services:
  - type: web
    name: ecommerce-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        value: mongodb+srv://hritik1972:Hritik1972@cluster0.ukj019o.mongodb.net/ecommerce?retryWrites=true&w=majority&appName=Cluster0
      - key: DATABASE_NAME
        value: ecommerce
